### ISSUE TITLE
Register entry post on database before verify otp 

### ISSUE THREAD

**Issue by abdulkarimkhorajiya** [akrajilwar/Android-Login-And-Registration#1]
hello sir,

please upload new project for register entry are store after verify otp
before verify opt register not insert on database.

if user are not otp verify then not entry will be post on database how to resolve
if new updated are post then mail me on this email id : abdulkarimkhorajiya@gmail.com

**Comment by akrajilwar** [comment]
the project I've uploaded support email verification.

**Comment by abdulkarimkhorajiya** [comment]
my below conversion is logic realted not error related.
==================================================
you uploaded this project . all are successfully run email verification code will be sent.
but if you notice without verify otp             
register entry are store on database
when if you are not verify otp and go to the second time register page then message print already register.
this small mistakes 

my question is simple. if you left from verify otp page then go to the second time register so you can register. if you not verify otp second time otp send while the user not verify otp at that time email already register message not shown and register entry are not store on database while otp verification not match.

if you want to check then 

1) register your email if email is already on database then remove and register.
2) while you go to the verify otp page. 
without otp varify you leave this verify page. and check database register entry store.

otp is not meaningful if user without verification.

**Comment by abrshdir** [comment]
You did good job my friend, but it has a problem with verification....otp sent to email doesnt let u pass to the next step. Shows this error.--> ***Json error: value <br of type java.lang.String cannot be converted to jsonobject**** any solutions to this?

**Comment by abrshdir** [comment]
SOLVED! Avoid error when creating a database!
