### ISSUE TITLE
database statement

### ISSUE THREAD

**Issue by mazemingw** [akrajilwar/Android-Login-And-Registration#5]
OTP INT (6) not null, which should be OTP INT (6) not null, and OTP INT (6) not null,
There's a problem with the database statement
My English is not very good, but thank you for your project

**Comment by akrajilwar** [comment]
> OTP INT (6) not null, which should be OTP INT (6) not null, and OTP INT (6) not null,
> There's a problem with the database statement
> My English is not very good, but thank you for your project

check here
https://www.androidlearning.com/android-login-registration-with-php-mysql-sqlite/
